version: 2.1

jobs:
  # Job 1: Sync the repository with a shallow clone
  sync-repo:
    machine:
      image: ubuntu-2004:202010-01
      resource_class: large
    steps:
      - checkout
      - run:
          name: Install Repo and Sync Dependencies
          command: |
            sudo apt update
            sudo apt install -y git python3 curl repo
      - run:
          name: Perform Shallow Repo Sync
          command: |
            mkdir llvm-toolchain
            cd llvm-toolchain
            repo init -u https://android.googlesource.com/platform/manifest -b llvm-toolchain --depth=1
            repo sync -c --no-tags --optimized-fetch --depth=1
            du -sh .
      - persist_to_workspace:
          root: .
          paths:
            - llvm-toolchain

  # Job 2: Build the toolchain
  build-toolchain:
    machine:
      image: ubuntu-2004:202010-01
      resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Build Dependencies
          command: |
            sudo apt update
            sudo apt install -y clang bison llvm llvm-dev python3 lld ninja-build cmake crossbuild-essential-arm64
      - run:
          name: Build the Toolchain
          command: |
            cd llvm-toolchain
            python3 toolchain/llvm_android/build.py --no-build windows --skip-tests --single-stage --no-musl
      - persist_to_workspace:
          root: .
          paths:
            - llvm-toolchain/out/stage2

  # Job 3: Apply custom modifications for the aarch64 NDK build
  build-ndk:
    machine:
      image: ubuntu-2004:202010-01
      resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Clone Custom AARCH64 NDK Repository
          command: |
            git clone https://github.com/SnowNF/ndk-aarch64-linux.git ndk-source
      - run:
          name: Replace Source in Toolchain
          command: |
            cd llvm-toolchain/toolchain/llvm_android
            mv patches ../patches
            rm -rf *
            cp -rf ../../ndk-source/* .
            mv ../patches patches
      - persist_to_workspace:
          root: .
          paths:
            - llvm-toolchain/toolchain/llvm_android

  # Job 4: Package the final NDK and store as an artifact
  package-and-upload:
    machine:
      image: ubuntu-2004:202010-01
      resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Package Final NDK
          command: |
            mkdir final-ndk
            cp -r llvm-toolchain/toolchain/llvm_android final-ndk/
            tar -czvf ndk-aarch64.tar.gz final-ndk
      - store_artifacts:
          path: ndk-aarch64.tar.gz
          destination: ndk-aarch64.tar.gz

workflows:
  version: 2
  build_ndk:
    jobs:
      - sync-repo
      - build-toolchain:
          requires:
            - sync-repo
      - build-ndk:
          requires:
            - build-toolchain
      - package-and-upload:
          requires:
            - build-ndk
