name: Setup Windows RDP with Pinggy

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Enable RDP
        run: |
          Enable-RemoteDesktop
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes

      - name: Set RDP User Password
        run: |
          net user Administrator YourStrongPassword
        shell: powershell

      - name: Download Pinggy
        run: |
          Invoke-WebRequest -Uri https://github.com/pinggy-io/pinggy/releases/latest/download/pinggy-windows-amd64.exe -OutFile pinggy.exe
          Move-Item pinggy.exe C:\Windows\System32
        shell: powershell

      - name: Start Pinggy Tunnel
        run: |
          Start-Process -FilePath "pinggy.exe" -ArgumentList "tcp --port 3389" -NoNewWindow -PassThru
        shell: powershell

      - name: Get Pinggy Tunnel URL
        run: |
          Start-Sleep -Seconds 5
          (Invoke-WebRequest -Uri "http://127.0.0.1:4040/api/tunnels" | ConvertFrom-Json).tunnels | Where-Object {$_.proto -eq "tcp"} | ForEach-Object {Write-Output "Pinggy RDP URL: $($_.public_url)"}
        shell: powershell
