name: Setup RDP on Windows with Serveo

on: 
  workflow_dispatch:
    inputs:
      subdomain:
        description: 'Subdomain for serveo (e.g., my-unique-subdomain)'
        required: true
        default: 'my-unique-subdomain'

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install OpenSSH
      run: |
        choco install openssh -y

    - name: Start Serveo Tunnel
      run: |
        Start-Process -FilePath "C:\Program Files\OpenSSH-Win64\ssh.exe" -ArgumentList "-R ${{ github.event.inputs.subdomain }}.serveo.net:3389:localhost:3389 serveo.net" -NoNewWindow -Wait

    - name: Delay for 10 hours
      run: |
        timeout /t 36000

    - name: Display RDP Connection Instructions
      run: |
        echo "RDP setup complete. To connect, use the RDP client on your phone and connect to the hostname: ${{ github.event.inputs.subdomain }}.serveo.net"
