name: Setup Pterodactyl Panel with LocalTunnel

on:
  push:
    branches:
      - main

jobs:
  setup-pterodactyl:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Dependencies
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl wget sudo lsb-release apt-transport-https software-properties-common

      # Step 2: Install Docker
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER

      # Step 3: Install Pterodactyl Panel Dependencies
      - name: Install Pterodactyl Panel Dependencies
        run: |
          sudo apt install -y python3 python3-pip python3-dev libffi-dev libssl-dev git unzip

      # Step 4: Download and Install Pterodactyl Panel
      - name: Download and Install Pterodactyl Panel
        run: |
          sudo curl -Lo /tmp/panel.tar.gz https://github.com/pterodactyl/panel/releases/download/v1.0.0/panel.tar.gz
          cd /var/www
          sudo tar -xzvf /tmp/panel.tar.gz
          sudo chown -R www-data:www-data pterodactyl
          cd /var/www/pterodactyl
          sudo php composer.phar install --no-dev --optimize-autoloader

      # Step 5: Set Up Pterodactyl Panel Configuration
      - name: Set Up Pterodactyl Panel Configuration
        run: |
          sudo cp .env.example .env
          sudo php artisan key:generate
          sudo php artisan p:environment:setup
          sudo php artisan p:environment:database
          sudo php artisan migrate --seed --force

      # Step 6: Install LocalTunnel
      - name: Install LocalTunnel
        run: |
          sudo npm install -g localtunnel
          nohup lt --port 80 > localtunnel.log 2>&1 &

      # Step 7: Display LocalTunnel URL
      - name: Display LocalTunnel URL
        run: |
          sleep 5
          cat localtunnel.log | grep -o "https://[^ ]*"

      # Step 8: Keep Workflow Active for 10 Hours
      - name: Keep Workflow Active for 10 Hours
        run: sleep 36000
