name: Setup Linux with XFCE4 and VNC via Pinggy

on:
  push:
    branches:
      - main

jobs:
  setup-linux-vnc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install XFCE4 and VNC server
      - name: Install XFCE4 and VNC Server
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver wget
          mkdir -p ~/.vnc
          echo -e "yourpassword\nyourpassword\nn" | vncpasswd
          echo 'startxfce4' > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          vncserver -geometry 1920x1080 :1

      # Step 3: Download and setup Pinggy
      - name: Setup Pinggy Tunnel
        run: |
          curl -sL https://get.pinggy.io | bash
          nohup pinggy tcp 5901 > pinggy.log 2>&1 &

      # Step 4: Display Pinggy URL
      - name: Get Pinggy TCP URL
        run: |
          sleep 5
          cat pinggy.log | grep -o "tcp://[^ ]*"

      # Step 5: Keep workflow alive for 10 hours
      - name: Keep Alive for 10 Hours
        run: sleep 36000
