name: Setup Chrome Remote Desktop

on: 
  workflow_dispatch:

jobs:
  setup-crd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Chrome Remote Desktop
      run: |
        # Update package lists
        sudo apt-get update

        # Install necessary packages
        sudo apt-get install -y wget gdebi-core

        # Download Chrome Remote Desktop .deb package
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb

        # Install the .deb package
        sudo gdebi -n chrome-remote-desktop_current_amd64.deb

    - name: Install Desktop Environment
      run: |
        # Install XFCE desktop environment
        sudo apt-get install -y xfce4 xfce4-goodies

        # Configure Chrome Remote Desktop to use XFCE
        echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > ~/.chrome-remote-desktop-session

    - name: Start Chrome Remote Desktop Service
      run: |
        # Start Chrome Remote Desktop service
        sudo systemctl enable chrome-remote-desktop@$USER
        sudo systemctl start chrome-remote-desktop@$USER

    - name: Authenticate and Setup Chrome Remote Desktop
      run: |
        # Authenticate Chrome Remote Desktop and set up with PIN
        echo -e "123456\n123456\n" | DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AanRRru81f9l4fh7SBRJM95pglRhFVKrkgm_EoE1Dk8ypMoO7Cs_4iw1Gand-DeYiTF4CA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
    - name: Delay for 10 hours
      run: |
        # Delay execution for 10 hours (36000 seconds)
        sleep 36000

    - name: Display CRD Setup Instructions
      run: |
        echo "Chrome Remote Desktop setup complete. To finish setup, visit https://remotedesktop.google.com/headless and follow the instructions to authorize your account."
