name: Setup Chrome Remote Desktop

on:
  push:
    branches:
      - main

jobs:
  setup-chrome-remote-desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update package list
        run: sudo apt-get update

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y
          rm google-chrome-stable_current_amd64.deb

      - name: Install Chrome Remote Desktop
        run: |
          sudo apt-get install chrome-remote-desktop -y
          # Add your user to the chrome-remote-desktop group
          sudo usermod -a -G chrome-remote-desktop $USER

      - name: Set up Chrome Remote Desktop
        run: |
          # Replace 'your-email@gmail.com' with your Google account email
          echo "export CHROME_REMOTE_DESKTOP_DEFAULT_DESKTOP_SESSION=xfce" >> ~/.bashrc
          echo "export DISPLAY=:1" >> ~/.bashrc
          echo "bzakyan@gmail.com" > ~/.chrome-remote-desktop-session
          # Start the desktop environment
          startxfce4 &
          # Start Chrome Remote Desktop
          chrome-remote-desktop --start

      - name: Clean up
        run: sudo apt-get clean
