name: Setup Windows with Chrome Remote Desktop

on:
  push:
    branches:
      - main

jobs:
  setup-windows-crd:
    runs-on: windows-latest

    steps:
      # Step 1: Download Chrome Remote Desktop
      - name: Download Chrome Remote Desktop Installer
        run: |
          curl -L -o crd_installer.exe https://dl.google.com/chrome-remote-desktop/chrome-remote-desktop_current.exe

      # Step 2: Install Chrome Remote Desktop
      - name: Install Chrome Remote Desktop
        run: |
          start /wait crd_installer.exe /silent /install

      # Step 3: Display Setup Instructions
      - name: Display Chrome Remote Desktop Setup Instructions
        run: |
          echo "1. Open the Actions tab and find this workflow."
          echo "2. Download and install the Chrome browser (if not already installed)."
          echo "3. Go to https://remotedesktop.google.com/headless and sign in with your Google account."
          echo "4. Set up a remote access code for this device."
          echo "5. Follow the instructions to link this machine to your Google account."
          echo "6. Use the Chrome Remote Desktop app on your mobile device or another computer to connect."
          echo "Keep this workflow alive using the sleep step below."

      # Step 4: Keep workflow active for 10 hours
      - name: Keep Workflow Active for 10 Hours
        run: timeout /t 36000
