name: Setup Linux with XFCE4 and VNC via LocalTunnel

on:
  push:
    branches:
      - main

jobs:
  setup-linux-vnc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install XFCE4 and VNC server
      - name: Install XFCE4 and VNC Server
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver wget npm
          mkdir -p ~/.vnc
          echo -e "yourpassword\nyourpassword\nn" | vncpasswd
          echo 'startxfce4' > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          vncserver -geometry 1920x1080 :1

      # Step 3: Install LocalTunnel and expose VNC
      - name: Install LocalTunnel
        run: |
          sudo npm install -g localtunnel
          nohup lt --port 5901 > localtunnel.log 2>&1 &

      # Step 4: Display LocalTunnel URL
      - name: Get LocalTunnel URL
        run: |
          sleep 5
          cat localtunnel.log | grep -o "https://[^ ]*"

      # Step 5: Keep workflow alive for 10 hours
      - name: Keep Alive for 10 Hours
        run: sleep 36000
