name: Setup Chrome Remote Desktop

on: 
  workflow_dispatch:

jobs:
  setup-crd:
    runs-on: windows-latest

    steps:
    - name: Install Chrome Remote Desktop
      run: |
        # Download Chrome Remote Desktop installer
        Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chrome-remote-desktop.msi"

        # Install the MSI package
        Start-Process -FilePath "msiexec.exe" -ArgumentList "/i chrome-remote-desktop.msi /quiet /norestart" -Wait

        # Remove installer to save space
        Remove-Item -Path "chrome-remote-desktop.msi"

    - name: Configure Chrome Remote Desktop
      run: |
        # Set PIN and authenticate Chrome Remote Desktop
        $PIN = "123456"  # Replace with your desired 6-digit PIN
        & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" `
           --code="4/0AanRRrtHlba-BI2CVyC8Sz4b1N9alq_VwyUn2kWj_bD2Dwu0vMKMYJJ_mEhH0OAmtwtS8A" `
           --redirect-url="https://remotedesktop.google.com/_/oauthredirect" `
           --name=$Env:COMPUTERNAME `
           --pin=$PIN


    - name: Delay for 10 hours
      run: |
        # Keep the workflow running for 10 hours
        timeout /t 36000

    - name: Display Completion Message
      run: |
        echo "Chrome Remote Desktop setup complete. Access it through https://remotedesktop.google.com/access"
